version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_app
    ports:
      - "3000:3000"
    environment:
      # Option A: as mapping (unquoted values, no “:=” inside quotes):
      MB_PASSWORD_COMPLEXITY: normal
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped

volumes:
  metabase_data:
